---
- name: Configure Cisco IOS device
  hosts: R1
  gather_facts: false
  connection: network_cli
  vars:
    intf_name: GigabitEthernet 1
    intf_description: Main network backbone 
  tasks:
  - name: Configure interface
    ios_config:
      lines:
      - "interface {{ intf_name }}"
      - "description {{ intf_description }}"
   
- name: Configure Cisco IOS device
  hosts: R2
  gather_facts: false
  connection: network_cli
  vars:
    intf_name: GigabitEthernet 1
    intf_description: Main network backbone 
  tasks:
  - name: Configure interface
    ios_config:
      lines:
      - "interface {{ intf_name }}"
      - "description {{ intf_description }}"