---
- name: Backup router running configuration
  hosts: routers
  connection: network_cli
  gather_facts: false


  tasks:
  
    - name: configure settings 
   
  cisco.ios.ios_config:
    lines:
    - description test interface
    - ip address 172.31.1.1 255.255.255.0
    parents: interface gigbitethernet 2
  