---
- name: create users from csv file
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - /etc/ansible/inventories/username.csv
   
  tasks:
  - name: Parse CSV To YAML
    template:
      src: /etc/ansible/inventories/username.csv
      dest: /etc/ansible/inventories/host.yaml
    run_once: true
  
  
  
  
  
  
  #  - name: reading the csv file
  #    read_csv:
  #     path: /etc/ansible/inventories/username.csv
  #    register: user_list
  #    delegate_to: localhost

  #  - name: display user_list data
  #    debug:
  #     var: user_list.list

  #  - community.windows.win_domain_user:
  #     name: "{{ first_name }}"
  #     description: user account for routers and switches
  #     password: "{{ user_list.password }}"
  #     upn: "{{ user_list.first_name user_list.last_name }}" 
  #     state: present
  #     update_password: when_changed
  #     password_never_expires: true
  #     account_locked: no
  #     enabled: yes
   
     