--- 
-
 hosts: firewall
 connection: local
 gather_facts: false
 
 vars:
  provider:
   ip_address: 192.168.68.187
   username: admin
   passworkd: GenDyn1234

 collections:
  - paloaltonetwork.panos
  
 tasks:
  - name: check if ready
    panos_check:
     ip_address: 192.168.68.187
     password: GenDyn1234