---
- name: Cisco show version
  hosts: routers
  gather_facts: false


  vars_files:



  tasks:
   - name: Gather OSPF Interfaces provided configurations
     cisco.ios.ios_ospf_interfaces:
      config:
      state: gathered  

   - name: show OSPF  interface configurations 
     debug:
       var: commands.stdout 
