---
- name: cisco
  hosts: R1
  gather_facts: false
  connection: network_cli

 
  tasks:

   - name: configure interface settings
     cisco.ios.ios_config:
      lines:
      - description loopback0 R1
      - ip address 172.31.1.1 255.255.255.255
      - ip ospf 21 area 0
      parents: interface Loopback0
      
      

- name: cisco
  hosts: R2
  gather_facts: false
  connection: network_cli

 
  tasks:

   - name: configure interface settings
     cisco.ios.ios_config:
      lines:
      - description loopback0 R2
      - ip address 172.31.1.2 255.255.255.255
      - ip ospf 21 area 0
      parents: interface Loopback0
      
 
- name: cisco
  hosts: R3
  gather_facts: false
  connection: network_cli

 
  tasks:

   - name: configure interface settings
     cisco.ios.ios_config:
      lines:
      - description loopback0 R3
      - ip address 172.31.1.3 255.255.255.255
      - ip ospf 21 area 0
      parents: interface Loopback0
