---
- name: Backup router running configuration
  hosts: routers
  connection: network_cli
  gather_facts: false

  tasks:

    - name: Backup router with cli_command
      cli_command:
        command: show run
      register: r_backup

    - name: Capture backup to control host
      vars:
      copy:
        content: "{{ r_backup.stdout }}"
        dest: "{{ inventory_hostname }}"
        