---
- name: Cisco show version
  hosts: routers
  gather_facts: false
  connection: network_cli

  vars: 
   R1: "{{ hostvars['R1']['ansible_host'] }}"
   R2: "{{ hostvars['R2']['ansible_host'] }}"


  tasks: 
  
  - name: Config R1 GRE
    ios_config:
     lines:
       - 'ip address 10.0.0.1 255.255.255.0'
       - 'tunnel source GigabitEthernet1'
       - 'tunnel destination {{ R2 }}'
       - 'ip OSPF 21 area 0'
       - 'ip mtu 1386'
     parents: interface Tunnel 0
    when: '"R1" in inventory_hostname'
  
  - name: Config R2 GRE
    ios_config:
      lines:
       - 'ip address 10.0.0.2 255.255.255.0'
       - 'tunnel source GigabitEthernet1'
       - 'tunnel destination {{ R1 }}'
       - 'ip OSPF 21 area 0'
       - 'ip mtu 1386'
      parents: interface Tunnel 0
    when: '"R2" in inventory_hostname'

 