---
- name: Cisco show version
  hosts: routers
  gather_facts: false
  connection: network_cli

  vars: 
   R1: "{{ hostvars['R1']['ansible_host'] }}"
   R2: "{{ hostvars['R2']['ansible_host'] }}"
   R3: "{{ hostvars['R3']['ansible_host'] }}"
   # change mtu size 
   MTU: "{{ 1350 }}"
   # IP ospf cost 
   cost: "{{ 1500 }}"

   


  tasks: 
  
  - name: Config R1 GRE
    ios_config:
     lines:
       - 'ip address 10.0.1.1 255.255.255.0'
       - 'description SIPR over Colorless Tunnel'
       - 'tunnel source GigabitEthernet1'
       - 'tunnel destination {{ R2 }}'
       - 'ip OSPF 21 area 0'
       - 'ip mtu {{ MTU }}'
       - 'no ip redirects'
       - 'no ip proxy-arp'
       - 'ip ospf cost {{ cost }}'
     parents: interface Tunnel 58600
    when: '"R1" in inventory_hostname'
  
  - name: Config R2 GRE
    ios_config:
      lines:
       - 'description SIPR over Colorless Tunnel'
       - 'ip ospf cost 1100'
       - 'ip address 10.0.1.2 255.255.255.0'
       - 'tunnel source GigabitEthernet1'
       - 'tunnel destination {{ R1 }}'
       - 'ip OSPF 21 area 0'
       - 'ip mtu {{ MTU }}'
       - 'no ip redirects'
       - 'no ip proxy-arp'
       - 'ip ospf cost {{ cost }}'
      parents: interface Tunnel 58600
    when: '"R2" in inventory_hostname'

  
  - name: Config R3 Hub
    ios_config:
      lines:
       - 'description SIPR over Colorless Tunnel'
       - 'ip ospf cost 1100'
       - 'ip address 10.0.1.2 255.255.255.0'
       - 'tunnel source GigabitEthernet1'
       - 'tunnel destination {{ R1 }}'
       - 'ip OSPF 21 area 0'
       - 'ip mtu {{ MTU }}'
       - 'no ip redirects'
       - 'no ip proxy-arp'
       - 'ip ospf cost {{ cost }}'
      parents: interface Tunnel 58600
    when: '"R3" in inventory_hostname'


 